name: gbo-env
channels:
  - defaults
  - conda-forge
  - ryanvolz
  
dependencies:
  - numpy
  - scipy
  - astropy
  - matplotlib
  - python=3.8
  - gnuradio=3.10
  - gnuradio-build-deps
  - sdrplay_api
