name: gbo-env
channels:
  - defaults
  - conda-forge
  - ryanvolz
  
dependencies:
  - numpy=1.13.3
  - scipy
  - astropy
  - matplotlib
  - python=3.6.5
  - gnuradio=3.9
  - gnuradio-build-deps
  - sdrplay_api
