name: gbo-env
channels:
  - defaults
  - conda-forge
  - ryanvoltz
  
dependencies:
  - numpy
  - scipy
  - astropy
  - matplotlib
  - python
  - gnuradio=3.10
  - gnuradio-build-deps
  - sdrplay_api
